spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:cache.yml,classpath:config.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: mate-im-auth
          uri: lb://mate-im-auth
          predicates:
            - Path=/auth/**,/token/**
        - id: mate-im-user
          uri: lb://mate-im-user
          predicates:
            - Path=/user/**
server:
  port: 8090