spring:
  data:
    redis:
      host: ${mate.im.redis.host}
      port: ${mate.im.redis.port}
      password: ${mate.im.redis.password}
      ssl:
        enabled: true
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: ${mate.im.redis.password}
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://${mate.im.redis.host}:${mate.im.redis.port}"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"